### ISSUE TITLE
Current page changes before data is updated

### ISSUE THREAD

**Issue by graindeweb** [infusion/jQuery-Paging#17]
Hi,

I've got a problem with ajax and jQuery-Paging: when user clicks on a link in pager, the current pages change before data are updated.
Is there a solution to change current number after data arrived?

Thanks (and sorry for my poor english)

**Comment by infusion** [comment]
Hi,

interesting use case! I just added a raw interface to the onClick handler. I added a simple example page here: https://github.com/infusion/jQuery-Paging/blob/master/example/onclick.html

I haven't published it, just pushed the commit to github. Could you please confirm that this fix works for you?

Robert
