### ISSUE TITLE
FEATURE: Option for enabling circular navigation needed

### ISSUE THREAD

**Issue by happyhj** [infusion/jQuery-Paging#18]
Hi,

It would be a lot useful if there is an option to enable circular navigation.

What I'm saying is like below.

![ezgif-3477513281](https://cloud.githubusercontent.com/assets/3903575/11175914/f686feae-8c7a-11e5-9c0d-955f886966c7.gif)

I tried to implement this with `onSelect` event handler, but `onSelect` event is not triggred when click prev button at first page.

Thanks a lot

**Comment by infusion** [comment]
That's a really nice feature! Thanks for the report, I'll implement this.

**Comment by happyhj** [comment]
@infusion 
If you are not start implementation yet.
You can consider my implementation.

**Comment by infusion** [comment]
Maybe we were thinking in two directions. Do you want the navigation to be navigable and clickable as well or are you fine with the calculation?
Could you please add a simple example to the example folder, illustrating the use case?

Calling the option `circular` seems fine :)

**Comment by infusion** [comment]
I pushed a more general circular implementation. Could you please check it out in the examples folder?

**Comment by happyhj** [comment]
I checked `/example/circular.html`.
This is exactly what I needed. :+1: :+1: 
Thank you for accepting my proposal and quick implementation. :)

**Comment by infusion** [comment]
You're welcome :)
