### ISSUE TITLE
Slicing without hashchange

### ISSUE THREAD

**Issue by sasoriza** [infusion/jQuery-Paging#22]
Is it possible to use slicing without using the hashchange library?
Alternatively, would it be possible to modify the hashchange function to not actually display the hashtag when changing the page?

>     <script type="text/javascript">
>         $j(document).ready(function(){
>             (function() {
> 
>                 var prev = {
>                     start: 0,
>                     stop: 0
>                 };
> 
> 
>                 var content = $j('.review-list');
> 
>                 var Paging = $j(".pagination").paging(content.length, {
>                     onSelect: function() {
> 
>                         var data = this.slice;
> 
>                         content.slice(prev[0], prev[1]).css('display', 'none');
>                         content.slice(data[0], data[1]).fadeIn("slow");
> 
>                         prev = data;
> 
>                         return true;
>                     },
>                     onFormat: function(type) {
> 
>                         switch (type) {
> 
>                         case 'block':
> 
>                             if (this.value != this.page)
>                                 return '<li><a href="#' + this.value + '">' + this.value + '</a></li>';
>                             else                                
>                                 return '<li class="current">' + this.value + '</li>';
> 
>                         case 'next':
> 
>                             if (this.active)
>                                 return '<li><a href="#' + this.value + '" class="next i-next" title="<?php echo $this->__('Next') ?>"></a></li>';
>                             ;
> 
>                         case 'prev':
> 
>                             if (this.active)
>                                 return '<li><a href="#' + this.value + '" class="previous i-previous" title="<?php echo $this->__('Previous') ?>"></a></li>';
>                             ;
> 
>                         case "leap":
> 
>                             if (this.active)
>                                 return "<li><span class='leap'>...</span></li>";
>                             return "";
> 
>                         }
>                     },
>                     format: '[< ncnnn! >]',
>                     perpage: 10,
>                     lapping: 0,
>                     page: null
>                 });
> 
> 
>                 $j(window).hashchange(function() {
> 
>                     if (window.location.hash)
>                         Paging.setPage(window.location.hash.substr(1));
>                     else
>                         Paging.setPage(1);
>                 });
> 
>                 $j(window).hashchange();
>             })();
>         });
>     </script>

**Comment by infusion** [comment]
The hashchange library is just for demo purposes, that it's possible to postpone the page setting and get it via a callback (such as the hash-change). The only thing you need to do is removing the hashchange lines and set `page: null` to `page: 1`, or whatever page you would like to start with. The slicing has nothing to do with the hash.

**Comment by sasoriza** [comment]
I see. So the # being added to the url is a default feature of your library since it is still being added after removing the hashchange lines.
Is it possible to not add anything to the url when moving through pages?

**Comment by infusion** [comment]
Oh yes of course. Simply return false in `onSelect`, instead of true. That means that the default behavior of the link is omitted, like `preventDefault`.

**Comment by sasoriza** [comment]
Beautiful, exactly what I needed, thank you so much!
