### ISSUE TITLE
Scroll to top of list on pagination click

### ISSUE THREAD

**Issue by sasoriza** [infusion/jQuery-Paging#23]
You mention a scrollTo plugin on your page that enables the blue dots to scroll to a position on the page. Sadly this doesn't work and I was wondering what you would sugggest to allow scrolling to the top of the list when clicking on a pagination entry.
Thanks!

**Comment by infusion** [comment]
Sorry, the used plugin in `paging.demo.min.js` had a bug. I fixed it there.
