### ISSUE TITLE
How to identify the current page

### ISSUE THREAD

**Issue by jncraig** [infusion/jQuery-Paging#24]
In onFormat, is it possible to know which is the current (c) page?

If so, how?

I'm trying to set a special class on the current page link.

**Comment by infusion** [comment]
Yes sure, the current page is the `page` attribute

**Comment by jncraig** [comment]
Thanks.  After leaving the question. I fiund some code in one of your
examples that was the key.  All is working now.

Thank you for this nice plugin!
