### ISSUE TITLE
P and q in format option

### ISSUE THREAD

**Issue by jncraig** [infusion/jQuery-Paging#25]
I need some help with these.

I want to have previous block and next block links in the paging.  Can I do that?  Does it involve p and q?

**Comment by infusion** [comment]
Yes, try the format string "(qq -) nnncnnn (- pp)".

**Comment by jncraig** [comment]
I used format: '[(qq-) nnncnnn (-pp)]'

I get undefinedundefinedundefined  in the positions where -qq and -pp occur
in the format string.

**Comment by infusion** [comment]
did you adjust the onFormat callback for your needs?

**Comment by jncraig** [comment]
No I didn't, mostly because I'm not sure how to make the needed
adjustments.  Can you please provide a little more quidance?

**Comment by infusion** [comment]
A `format`-string like "nncnn" is parsed character by character and for each character you get the `onFormat` callback called. Inside the callback you need to decide what HTML you want to get printed to the dom. The following mapping is used for character to types:
```
                        "[": "first",
                        "]": "last",
                        "<": "prev",
                        ">": "next",
                        "q": "left",
                        "p": "right",
                        "-": "fill",
                        ".": "leap"
```
This means inside the 

```
onFormat: function(type) {

}
```
callback, you typically add a switch/case statement for each type, like

```
switch (type) {
case 'prev':
   return '<a href="#' + this.value + '" class="prev">&laquo; Previous</a>';
}
```

See a more detailed example in the jquery.paging.js file on line 113.

**Comment by jncraig** [comment]
I'm still not getting this.  Using your example, p & q return last and first pages.

I would like p & q to move me to the next set of pages, with the active page being set to a block ahead or behind the current active pages.

I have [nncnn] set as the format, and that works just fine.

**Comment by infusion** [comment]
What do you mean by next set of pages?

**Comment by jncraig** [comment]
I see 5 pages at a time with the nncnn.  So, the first display is 1 2 3 4 5, with 1 as active.

If I use right, I'd see 6 5 8 9 10, with 8 active.  Then 11 12 13 14 15 with 13 active.

The left links would go in the other direction similarly.

**Comment by infusion** [comment]
Ahh, you want to go block-wise. Wait a minute, I'll add an option to do that.

**Comment by infusion** [comment]
Sorry, it took me while to find a good solution for it, but I'm quite satisfied now. I introduced a new options variable `stepwidth`. For any `stepwidth>0` you determine for how many steps a left/right click has to jump, default = 1. The behavior you desire to jump block-wise is available with `stepwidth=0`. See examples/basic.html

**Comment by jncraig** [comment]
Thanks a million!  I think that will work just fine for me.

I really do appreciate it when open-source authors provide first class
support.  So thank you for that, too.

**Comment by infusion** [comment]
Thanks for your kind words :)
